# Generated by Django 2.2.3 on 2019-07-10 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of the task')),
                ('description', models.CharField(max_length=500, null=True, verbose_name='Detail of the task')),
                ('is_done', models.BooleanField(default=False, verbose_name='Is the task done?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Create timestamp')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Update timestamp')),
            ],
        ),
    ]
